export const TOPICS = {
  PING_EVENTS: {
    name: 'ping-events',
    retention: 7 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  MONITOR_STATE: {
    name: 'monitor-state',
    retention: -1,
    cleanup: 'compact' as const,
    partitions: 6,
  },
  MONITOR_EVALUATIONS: {
    name: 'monitor-evaluations',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  ALERT_TRIGGERS: {
    name: 'alert-triggers',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 3,
  },
  INCIDENT_EVENTS: {
    name: 'incident-events',
    retention: 7 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  ALERT_RETRIES: {
    name: 'alert-retries',
    retention: 1 * 86400000,
    cleanup: 'delete' as const,
    partitions: 3,
  },
  ALERT_DEADLETTER: {
    name: 'alert-deadletter',
    retention: 30 * 86400000,
    cleanup: 'delete' as const,
    partitions: 1,
  },
  JOB_TRIGGERS: {
    name: 'job-triggers',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  JOB_RESULTS: {
    name: 'job-results',
    retention: 7 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  JOB_RETRY_SCHEDULED: {
    name: 'job-retry-scheduled',
    retention: 1 * 86400000,
    cleanup: 'delete' as const,
    partitions: 3,
  },
  JOB_RUN_LOGS: {
    name: 'job-run-logs',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 3,
  },
  WORKFLOW_RESUME: {
    name: 'workflow-resume',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  WORKFLOW_SIGNALS: {
    name: 'workflow-signals',
    retention: 7 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
  WORKFLOW_STEP_RESULTS: {
    name: 'workflow-step-results',
    retention: 3 * 86400000,
    cleanup: 'delete' as const,
    partitions: 6,
  },
} as const;

export const CONSUMER_GROUPS = {
  SINK: 'kast-sink',
  SCHEDULER: 'kast-scheduler',
  INCIDENTS: 'kast-incidents',
  INCIDENTS_PINGS: 'kast-incidents-pings',
  NOTIFY: 'kast-notify',
  NOTIFY_RETRIES: 'kast-notify-retries',
  WS_PING: 'kast-ws-ping-events',
  WS_STATE: 'kast-ws-monitor-state',
  WS_INCIDENTS: 'kast-ws-incident-events',
  JOB_EXECUTOR: 'kast-job-executor',
  JOB_SINK: 'kast-job-sink',
  JOB_BRIDGE: 'kast-job-bridge',
  WS_JOB_RESULTS: 'kast-ws-job-results',
  JOB_RETRY: 'kast-job-retry',
  JOB_LOG_SINK: 'kast-job-log-sink',
  WS_JOB_LOGS: 'kast-ws-job-logs',
  WORKFLOW_ENGINE: 'kast-workflow-engine',
  WORKFLOW_SLEEPER: 'kast-workflow-sleeper',
  WORKFLOW_SIGNAL_DELIVERY: 'kast-workflow-signal-delivery',
  WS_WORKFLOW_STEPS: 'kast-ws-workflow-steps',
} as const;
